# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/v1/trees"
  to = "https://moretrees-api.herokuapp.com/api/v1/trees"
  status = 200
  force = true
  headers = {X-From = "netlify"}

[[redirects]]
  from = "/api/v1/users/*"
  to = "https://moretrees-api.herokuapp.com/api/v1/users"
  status = 200
  force = true
  headers = {X-From = "netlify"}

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/*"
#     [headers.values]
#     Access-Control-Allow-Origin = "https://moretrees.herokuapp.com"